-- ============================================================
-- ST_PROCESS_LEADS_TO_CONTACTS.sql
-- Merger leads til contacts og permissions fra leads → contacts
-- ============================================================
-- DID - Author: Tim Devoldere
-- DID - CreationDate: 2023-10-04
-- DID - Version: 0.1.0
-- DID - LastModifiedBy: Peter Langkilde
-- DID - ModifiedDate: 2026-04-08
-- ============================================================
-- ÆNDRINGER (12. maj 2026):
--   [TODO] OPTIN_DT:    > → < i MERGE MATCHED (beholde ældste, ikke nyeste)
--   [TODO] MODIFIED_DT: GETDATE() → faktisk ændringstidspunkt fra SOURCE
--   [TODO] MODIFIED_DT: mangler i WHEN NOT MATCHED INSERT-grenen
-- ============================================================

AS
BEGIN
	BEGIN TRY
		DECLARE @MSG NVARCHAR(4000) = '';

		SET @MSG = '{"event_type":"INFO","msg":"START PROCEDURE"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;

		IF OBJECT_ID('TMP_LEADS_IN_SCOPE') IS NOT NULL
			BEGIN
				DROP TABLE dbo.TMP_LEADS_IN_SCOPE;
			END

		CREATE TABLE dbo.TMP_LEADS_IN_SCOPE(LEADID INT, CONTACTID INT);
		CREATE INDEX IDX_LEADID_CONTACTID ON dbo.TMP_LEADS_IN_SCOPE(LEADID, CONTACTID);

		SET @MSG = '{"event_type":"INFO","msg":"TMP TABLE CREATED"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;

		-- Find leads der matcher en eksisterende contact på mail
		-- og som ikke allerede har en igangværende REMOVE-request
		INSERT INTO dbo.TMP_LEADS_IN_SCOPE(LEADID, CONTACTID)
		SELECT 
			UL.ID
			, UC.ID
		FROM dbo.USERS_LEADS UL WITH (NOLOCK)
		INNER JOIN dbo.USERS_USER_CONTACTS UC WITH (NOLOCK) ON UC.MAIL = UL.MAIL
		WHERE NOT EXISTS (SELECT 1
						FROM dbo.SELLIGENT_REGULATORY_REQUESTS requests 
						WHERE requests.[STATUS] < 10
						AND requests.[REQUEST_TYPE] = 'REMOVE'
						AND requests.[REQUEST_FILTER] = '[{"Field":"ID","Value":"' + CONVERT(NVARCHAR(20), UL.ID ) + '"}]'
						AND requests.[REQUEST_TARGET] =  '[795]'							
					);

		SET @MSG = '{"event_type":"INFO","msg":"TMP TABLE FILLED"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;

		-- Opdater USERS_USER_CONTACTS med nyeste optout/bounce fra lead
		-- kun hvis lead-posten er nyere end contact-posten
		UPDATE UC SET
		    CAMPAIGN_ID = UL.CAMPAIGN_ID
			, OPTOUT = CASE WHEN COALESCE(UL.OPTOUT_DT, '1900-01-01') > COALESCE(UC.OPTOUT_DT, '1900-01-01') THEN UL.OPTOUT ELSE UC.OPTOUT END
			, OPTOUT_SOURCE = CASE WHEN COALESCE(UL.OPTOUT_DT, '1900-01-01') > COALESCE(UC.OPTOUT_DT, '1900-01-01') THEN CASE WHEN COALESCE(UL.OPTOUT , 0) <> 0 THEN 'Lead Record' ELSE NULL END ELSE UC.OPTOUT_SOURCE END
			, OPTOUT_DT = CASE WHEN COALESCE(UL.OPTOUT_DT, '1900-01-01') > COALESCE(UC.OPTOUT_DT, '1900-01-01') THEN UL.OPTOUT_DT ELSE UC.OPTOUT_DT END			
			, BOUNCECNT = CASE WHEN COALESCE(UL.BOUNCEDT, '1900-01-01') > COALESCE(UC.BOUNCEDT, '1900-01-01') THEN UL.BOUNCECNT ELSE UC.BOUNCECNT END			
			, BOUNCEDT = CASE WHEN COALESCE(UL.BOUNCEDT, '1900-01-01') > COALESCE(UC.BOUNCEDT, '1900-01-01') THEN UL.BOUNCEDT ELSE UC.BOUNCEDT END		
		FROM dbo.USERS_USER_CONTACTS UC
		INNER JOIN dbo.TMP_LEADS_IN_SCOPE T ON T.CONTACTID = UC.ID
		INNER JOIN dbo.USERS_LEADS UL ON UL.ID = T.LEADID
		WHERE COALESCE(UL.MODIFIED_DT, UL.CREATED_DT) > COALESCE(UC.MODIFIED_DT, UC.CREATED_DT);

		-- Opdater DATA_EXT_CONTACT med kampagne, B2B_FILTER og produktvælger
		UPDATE EC SET
    	    CAMPAIGN_ID = UL.CAMPAIGN_ID
		    , B2B_FILTER = CASE WHEN UL.B2B_FILTER IS NOT NULL THEN UL.B2B_FILTER ELSE EC.B2B_FILTER END
		    , PRODUKTVAELGER_RESPONSE = CASE WHEN UL.PRODUKTVAELGER_RESPONSE IS NOT NULL THEN UL.PRODUKTVAELGER_RESPONSE ELSE EC.PRODUKTVAELGER_RESPONSE END
			, MODIFIED = UL.MODIFIED_DT
		FROM dbo.DATA_EXT_CONTACT EC
		INNER JOIN dbo.TMP_LEADS_IN_SCOPE T ON T.CONTACTID = EC.USERID
		INNER JOIN dbo.USERS_LEADS UL ON UL.ID = T.LEADID
		WHERE EC.USERID IS NOT NULL;

		SET @MSG = '{"event_type":"INFO","msg":"CONTACTS UPDATED"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;

		-- Merger permissions fra DATA_PERMISSION_LEADS → DATA_DATA_PERMISSIONS
		MERGE dbo.DATA_DATA_PERMISSIONS AS TARGET
		USING (SELECT 
					UC.ID AS USERID
					, DPL.MODIFIED_DT
					, DPL.OPTIN_DT
					, DPL.OPTOUT_DT
					, DPL.OPTIN
					, DPL.CHANNEL_TYPE
					, DPL.OPTIN_SOURCE
					, DPL.OPTOUT_SOURCE
					, DPL.PERMISSION_VERSION					
				FROM dbo.DATA_PERMISSION_LEADS DPL
				INNER JOIN dbo.TMP_LEADS_IN_SCOPE T ON T.LEADID = DPL.USERID
				INNER JOIN dbo.USERS_USER_CONTACTS UC WITH (NOLOCK) ON T.CONTACTID = UC.ID) AS SOURCE
		ON SOURCE.USERID = TARGET.USERID AND SOURCE.CHANNEL_TYPE = TARGET.CHANNEL_TYPE
		WHEN MATCHED THEN UPDATE SET
			-- Beholder ÆLDSTE opt-in timestamp (første opt-in)
			TARGET.OPTIN_DT = CASE WHEN SOURCE.OPTIN_DT < TARGET.OPTIN_DT THEN SOURCE.OPTIN_DT ELSE TARGET.OPTIN_DT END
			, TARGET.OPTIN = CASE WHEN SOURCE.OPTIN_DT < TARGET.OPTIN_DT THEN SOURCE.OPTIN ELSE TARGET.OPTIN END
			, TARGET.OPTIN_SOURCE = CASE WHEN SOURCE.OPTIN_DT < TARGET.OPTIN_DT THEN SOURCE.OPTIN_SOURCE ELSE TARGET.OPTIN_SOURCE END
			-- Beholder NYESTE opt-out timestamp
			, TARGET.OPTOUT_DT = CASE WHEN SOURCE.OPTOUT_DT > TARGET.OPTOUT_DT THEN SOURCE.OPTOUT_DT ELSE TARGET.OPTOUT_DT END
			, TARGET.OPTOUT_SOURCE = CASE WHEN SOURCE.OPTOUT_DT > TARGET.OPTOUT_DT THEN SOURCE.OPTOUT_SOURCE ELSE TARGET.OPTOUT_SOURCE END
			, TARGET.PERMISSION_VERSION = CASE WHEN SOURCE.OPTOUT_DT > TARGET.OPTOUT_DT THEN SOURCE.PERMISSION_VERSION ELSE TARGET.PERMISSION_VERSION END
			-- MODIFIED_DT = seneste ændringstidspunkt (fra SOURCE hvis nyere end TARGET)
			, TARGET.MODIFIED_DT = CASE WHEN COALESCE(SOURCE.MODIFIED_DT, '1900-01-01') > COALESCE(TARGET.MODIFIED_DT, '1900-01-01') THEN SOURCE.MODIFIED_DT ELSE TARGET.MODIFIED_DT END
		WHEN NOT MATCHED THEN INSERT(
			USERID
			, CHANNEL_TYPE
			, OPTIN
			, OPTIN_DT
			, OPTIN_SOURCE
			, OPTOUT_DT
			, OPTOUT_SOURCE
			, MODIFIED_DT
			, PERMISSION_VERSION)
		VALUES(
			SOURCE.USERID
			, SOURCE.CHANNEL_TYPE
			, SOURCE.OPTIN
			, SOURCE.OPTIN_DT
			, SOURCE.OPTIN_SOURCE
			, SOURCE.OPTOUT_DT
			, SOURCE.OPTOUT_SOURCE
			, SOURCE.MODIFIED_DT
			, SOURCE.PERMISSION_VERSION);

		SET @MSG = '{"event_type":"INFO","msg":"PERMISSIONS MERGED"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;

		-- Opret REMOVE-requests for leads der nu er merged til contacts
		INSERT INTO dbo.SELLIGENT_REGULATORY_REQUESTS
		(
			[CREATED_DT]
			, [REQUESTED_BY]
			, [STATUS]
			, [REQUEST_TYPE]
			, [REQUEST_FILTER]
			, [REQUEST_TARGET]
		)
		SELECT DISTINCT
			CURRENT_TIMESTAMP																
			, 'ST_PROCESS_LEADS_TO_CONTACTS'															
			, 0																				
			, 'REMOVE'																		
			, '[{"Field":"ID","Value":"' + CONVERT(NVARCHAR(20), USRS.ID) + '"}]'	
			, '[795]'	
		FROM dbo.USERS_LEADS USRS WITH (NOLOCK)
		WHERE EXISTS(SELECT 1 FROM dbo.TMP_LEADS_IN_SCOPE T WITH (NOLOCK) WHERE T.LEADID = USRS.ID)
		AND NOT EXISTS (
							SELECT 1
							FROM dbo.SELLIGENT_REGULATORY_REQUESTS requests 
							WHERE requests.[STATUS] < 10
							AND requests.[REQUEST_TYPE] = 'REMOVE'
							AND requests.[REQUEST_FILTER] = '[{"Field":"ID","Value":"' + CONVERT(NVARCHAR(20), USRS.ID ) + '"}]'
							AND requests.[REQUEST_TARGET] =  '[795]'							
						);
		
		SET @MSG = '{"event_type":"INFO","msg":"END PROCEDURE"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;

	END TRY
	BEGIN CATCH
		SET @MSG = ERROR_MESSAGE();
		SET @MSG = '{"event_type":"ERROR","msg":"' + @MSG + '"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;
		RAISERROR(@MSG, 16, 1);
	END CATCH
END
