-- ============================================================
-- ST_PROCESS_LEADS_PERMISSIONS.sql
-- Opretter permissions-rækker for nye leads (channel type 1-5)
-- ============================================================
-- DID - Author: Tim Devoldere
-- DID - CreationDate: 2021-11-03
-- DID - Version: 0.1.0
-- DID - LastModifiedBy: Tim Devoldere
-- ============================================================
-- ÆNDRINGER (12. maj 2026):
--   [TODO] MODIFIED_DT: NULL → U.CREATED_DT (alle 5 channel types)
-- ============================================================

AS
BEGIN
	BEGIN TRY		
		DECLARE @MSG NVARCHAR(4000) = '';

		DECLARE @LAST_SYNC_ID    INT;
		DECLARE @CURRENT_SYNC_ID INT;

		SET @MSG = '{"event_type":"INFO","msg":"START PROCEDURE"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;

		SELECT @LAST_SYNC_ID    = CONVERT(INT, VALUE) FROM dbo.SETTINGS WITH (NOLOCK) WHERE NAME = 'LAST_SYNC_ID' AND MODULENAME = 'ST_PROCESS_LEADS_PERMISSIONS';
		SELECT @CURRENT_SYNC_ID = MAX(ID)             FROM dbo.USERS_LEADS U WITH (NOLOCK);

		SET @MSG = '{"event_type":"INFO","msg":"ID RANGE SELECTED"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;

        -- ── CHANNEL TYPE 1 ───────────────────────────────────────
		INSERT INTO dbo.DATA_PERMISSION_LEADS(
			  USERID
			, MODIFIED_DT
			, OPTIN_DT
			, OPTOUT_DT
			, OPTIN
			, CHANNEL_TYPE
			, OPTIN_SOURCE
			, OPTOUT_SOURCE
			, CREATED_DT)
		SELECT
			  U.ID            AS USERID
			, U.CREATED_DT    AS MODIFIED_DT
			, U.CREATED_DT    AS OPTIN_DT
			, NULL            AS OPTOUT_DT
			, 1               AS OPTIN
			, 1               AS CHANNEL_TYPE
			, 'ST_PROCESS_LEADS_PERMISSIONS' AS OPTIN_SOURCE
			, NULL            AS OPTOUT_SOURCE
			, GETDATE()       AS CREATED_DT
		FROM dbo.USERS_LEADS U WITH (NOLOCK)
		WHERE (ID > @LAST_SYNC_ID AND ID <= @CURRENT_SYNC_ID)
		AND NOT EXISTS (SELECT 1 FROM dbo.DATA_PERMISSION_LEADS DPL WITH (NOLOCK) WHERE DPL.USERID = U.ID AND DPL.CHANNEL_TYPE = 1);

        -- ── CHANNEL TYPE 2 ───────────────────────────────────────
        INSERT INTO dbo.DATA_PERMISSION_LEADS(
			  USERID
			, MODIFIED_DT
			, OPTIN_DT
			, OPTOUT_DT
			, OPTIN
			, CHANNEL_TYPE
			, OPTIN_SOURCE
			, OPTOUT_SOURCE
			, CREATED_DT)
		SELECT
			  U.ID            AS USERID
			, U.CREATED_DT    AS MODIFIED_DT
			, U.CREATED_DT    AS OPTIN_DT
			, NULL            AS OPTOUT_DT
			, 1               AS OPTIN
			, 2               AS CHANNEL_TYPE
			, 'ST_PROCESS_LEADS_PERMISSIONS' AS OPTIN_SOURCE
			, NULL            AS OPTOUT_SOURCE
			, GETDATE()       AS CREATED_DT
		FROM dbo.USERS_LEADS U WITH (NOLOCK)
		WHERE (ID > @LAST_SYNC_ID AND ID <= @CURRENT_SYNC_ID)
		AND NOT EXISTS (SELECT 1 FROM dbo.DATA_PERMISSION_LEADS DPL WITH (NOLOCK) WHERE DPL.USERID = U.ID AND DPL.CHANNEL_TYPE = 2);

        -- ── CHANNEL TYPE 3 ───────────────────────────────────────
        INSERT INTO dbo.DATA_PERMISSION_LEADS(
			  USERID
			, MODIFIED_DT
			, OPTIN_DT
			, OPTOUT_DT
			, OPTIN
			, CHANNEL_TYPE
			, OPTIN_SOURCE
			, OPTOUT_SOURCE
			, CREATED_DT)
		SELECT
			  U.ID            AS USERID
			, U.CREATED_DT    AS MODIFIED_DT
			, U.CREATED_DT    AS OPTIN_DT
			, NULL            AS OPTOUT_DT
			, 1               AS OPTIN
			, 3               AS CHANNEL_TYPE
			, 'ST_PROCESS_LEADS_PERMISSIONS' AS OPTIN_SOURCE
			, NULL            AS OPTOUT_SOURCE
			, GETDATE()       AS CREATED_DT
		FROM dbo.USERS_LEADS U WITH (NOLOCK)
		WHERE (ID > @LAST_SYNC_ID AND ID <= @CURRENT_SYNC_ID)
		AND NOT EXISTS (SELECT 1 FROM dbo.DATA_PERMISSION_LEADS DPL WITH (NOLOCK) WHERE DPL.USERID = U.ID AND DPL.CHANNEL_TYPE = 3);

        -- ── CHANNEL TYPE 4 ───────────────────────────────────────
        INSERT INTO dbo.DATA_PERMISSION_LEADS(
			  USERID
			, MODIFIED_DT
			, OPTIN_DT
			, OPTOUT_DT
			, OPTIN
			, CHANNEL_TYPE
			, OPTIN_SOURCE
			, OPTOUT_SOURCE
			, CREATED_DT)
		SELECT
			  U.ID            AS USERID
			, U.CREATED_DT    AS MODIFIED_DT
			, U.CREATED_DT    AS OPTIN_DT
			, NULL            AS OPTOUT_DT
			, 1               AS OPTIN
			, 4               AS CHANNEL_TYPE
			, 'ST_PROCESS_LEADS_PERMISSIONS' AS OPTIN_SOURCE
			, NULL            AS OPTOUT_SOURCE
			, GETDATE()       AS CREATED_DT
		FROM dbo.USERS_LEADS U WITH (NOLOCK)
		WHERE (ID > @LAST_SYNC_ID AND ID <= @CURRENT_SYNC_ID)
		AND NOT EXISTS (SELECT 1 FROM dbo.DATA_PERMISSION_LEADS DPL WITH (NOLOCK) WHERE DPL.USERID = U.ID AND DPL.CHANNEL_TYPE = 4);

        -- ── CHANNEL TYPE 5 ───────────────────────────────────────
        INSERT INTO dbo.DATA_PERMISSION_LEADS(
			  USERID
			, MODIFIED_DT
			, OPTIN_DT
			, OPTOUT_DT
			, OPTIN
			, CHANNEL_TYPE
			, OPTIN_SOURCE
			, OPTOUT_SOURCE
			, CREATED_DT)
		SELECT
			  U.ID            AS USERID
			, U.CREATED_DT    AS MODIFIED_DT
			, U.CREATED_DT    AS OPTIN_DT
			, NULL            AS OPTOUT_DT
			, 1               AS OPTIN
			, 5               AS CHANNEL_TYPE
			, 'ST_PROCESS_LEADS_PERMISSIONS' AS OPTIN_SOURCE
			, NULL            AS OPTOUT_SOURCE
			, GETDATE()       AS CREATED_DT
		FROM dbo.USERS_LEADS U WITH (NOLOCK)
		WHERE (ID > @LAST_SYNC_ID AND ID <= @CURRENT_SYNC_ID)
		AND NOT EXISTS (SELECT 1 FROM dbo.DATA_PERMISSION_LEADS DPL WITH (NOLOCK) WHERE DPL.USERID = U.ID AND DPL.CHANNEL_TYPE = 5);

		SET @MSG = '{"event_type":"INFO","msg":"PERMISSIONS GENERATED"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;

        UPDATE dbo.SETTINGS
        SET VALUE = @CURRENT_SYNC_ID
        WHERE NAME = 'LAST_SYNC_ID' AND MODULENAME = 'ST_PROCESS_LEADS_PERMISSIONS';

		SET @MSG = '{"event_type":"INFO","msg":"END PROCEDURE"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;

	END TRY
	BEGIN CATCH
		SET @MSG = ERROR_MESSAGE();
		SET @MSG = '{"event_type":"ERROR","msg":"' + @MSG + '"}';
		EXEC [dbo].[ST_LOGGING_SELLIGENT_ROUTINE] @MSG, @@PROCID;
		RAISERROR(@MSG, 16, 1);
	END CATCH
END
